#! /bin/csh -f

if ($#argv != 1) then
    echo "Usage $0 commit-message"
    exit 1
endif

# copy over latest
cp -r /Volumes/MusicAndData/Dev/Canon/OS\ X/Mac\ Pack/NSColor .
cp -r /Volumes/MusicAndData/Dev/Canon/iOS\ Packs/Foundation/Color\ Pack .

# old stuff
rm -rf build
rm .DS_Store
rm */.DS_Store
rm -rf *.xcodeproj/ericasadun.*

# git stuff
git add -A
git commit -m "$1"
git push


